baseURL = 'https://thekb.in'
languageCode = 'en-us'
title = 'Your Weekly Dispatch'
theme = 'PaperMod'

[params]
  defaultTheme = 'light'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false

  # Architecture Fixes
  ShowArchives = true
  disableSpecial1stPost = true
  ShowToc = false
  ShowWordCount = false

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Your Weekly Dispatch"
    Content = "A log of interesting content."

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 10
